data_dir: /arc/project/st-cdeboer-1/nick/PLA_seq_20240313

sample_size:
    MORF: 453403
    N80: 1969695

flank:
    MORF_r1: ^GCTTTATATATCTTGTGGAAAGGACGA...ACGCGTTAAGTCGACAATCA
    MORF_r2: ^GCAGCGTATCCACATAGCGTAAAAGGAGCAACATAGTTAAGAATACCAGTCAATCTTTCACAAATTTTGTAATCCAGAGGTTGATTGTCGACTTAACGCGT...TCGTCCTTTCCACAAGATAT
    N80_r1: ^TGCATTTTTTTCACATC...GGTTACGGCTGTT
    N80_r2: ^AACAGCCGTAACC...GATGTGAAAAAAATGCA

trimmed_len:
    MORF: 24
    N80: 80

samples:
    MORF_liquid_1: CTTACCGG-TGAAGACG
    MORF_semisolid_1: TCAAGCCG-TTACGTGA
    MORF_bead_1: ATGCGGTG-TAGTCGTG
    MORF_small_plate_1: AGGTAACA-ACCTTCAT
    MORF_large_plate_1: ACTAGAGA-ATAAGCCA
    MORF_liquid_2: AAGGAGTG-CTGTTCAA
    MORF_semisolid_2: TGCATACA-TAAGCTAG
    MORF_bead_2: TGGCCTAC-TGCTTAGA
    MORF_small_plate_2: CCTCTTCT-CGAGAATA
    MORF_large_plate_2: CGAGGAAG-CAGTTGAT
    MORF_liquid_3: AGATAAGC-CCAAGCTT
    MORF_semisolid_3: TACTCGAA-TCGGATGA
    MORF_bead_3: TCACGAAG-CCTATCAA
    MORF_small_plate_3: TGGATTGC-ATGGAATG
    MORF_large_plate_3: ACGAACCT-TCAATCCA
    MORF_liquid_4: CAGTAGCT-CGCCATAA
    MORF_semisolid_4: CTTAACAC-TCCGCCTA
    MORF_bead_4: TTGTTGAG-AACCGCGT
    MORF_small_plate_4: TCCGTGTT-AGGCATCT
    MORF_large_plate_4: CTGTCTAT-CCTTAGAT
    MORF_input_1: CGTTAATC-TAACTTGG
    MORF_input_2: TACGTGCA-CAATGACG
    MORF_input_3: TTACAGAG-CTGGCACT
    MORF_input_4: CAAGCGAG-AAGCCGAA
    N80_liquid_1: CCGTACAT-TTCAGTTG
    N80_semisolid_1: TACCTGGT-AGACCTCA
    N80_bead_1: AATGCCAA-ACGCACAA
    N80_small_plate_1: CTAGAACC-TTAGACCA
    N80_large_plate_1: ACTGGAAT-TTCACAGA
    N80_liquid_2: AGCATAGT-CTCGACTG
    N80_semisolid_2: TAACACCT-CTTGTTGG
    N80_bead_2: CAATGTGC-CATTACAG
    N80_small_plate_2: TCGATGCC-ACAACCGT
    N80_large_plate_2: TCTAACGC-AGTGATGA
    N80_liquid_3: CCAATAGT-TGGAGCAA
    N80_semisolid_3: AGCAGTCT-TGCGAATT
    N80_bead_3: ACTATTGC-ACACAGGA
    N80_small_plate_3: TACGATTC-CTCTTCCG
    N80_large_plate_3: TGCAGTGG-AAGAAGCT
    N80_liquid_4: TGCGAGGA-TAACCGTA
    N80_semisolid_4: ACGCCACA-TGGTTCGG
    N80_bead_4: CTTCGGTC-TAACGATG
    N80_small_plate_4: ACGGAGGT-AACTCTCG
    N80_large_plate_4: AGAATCAG-CTGTCGTA
